// Package apiroutes lists every HTTP API route owned by the WAF control plane.
package apiroutes

// AdministrativePaths is consumed by the runtime E2E self-management test.
// The httpserver contract test keeps it exactly synchronized with mux.Handle.
var AdministrativePaths = []string{
	"/api/setup/status", "/api/app/meta", "/api/app/ping", "/api/app/compat", "/api/app/compat/fix",
	"/api/settings/runtime", "/api/settings/management-hosts", "/api/settings/management-hosts/status", "/api/settings/direct-ip-access", "/api/settings/runtime/check-updates", "/api/settings/runtime/storage-indexes", "/api/public/login-appearance", "/api/public/healthcheck-appearance", "/api/login-appearance/preview/",
	"/api/owasp-crs/status", "/api/owasp-crs/check-updates", "/api/owasp-crs/update",
	"/api/auth/bootstrap", "/api/auth/login", "/api/auth/login/2fa", "/api/auth/passkeys/login/begin", "/api/auth/passkeys/login/finish", "/api/auth/providers", "/api/auth/oidc/start", "/api/auth/oidc/callback", "/api/auth/logout", "/api/auth/me", "/api/auth/2fa/status", "/api/auth/2fa/setup", "/api/auth/2fa/enable", "/api/auth/2fa/disable", "/api/auth/step-up/totp", "/api/auth/change-password", "/api/auth/login/2fa/passkey/begin", "/api/auth/login/2fa/passkey/finish", "/api/auth/passkeys", "/api/auth/passkeys/register/begin", "/api/auth/passkeys/register/finish", "/api/auth/passkeys/",
	"/api/sites", "/api/sites/", "/api/error-pages/preview/", "/api/upstreams", "/api/upstreams/", "/api/certificates", "/api/certificates/", "/api/tls-configs", "/api/tls-configs/", "/api/tls/auto-renew", "/api/certificate-materials/upload", "/api/certificate-materials/import-archive", "/api/certificate-materials/export", "/api/certificate-materials/export/", "/api/certificate-materials/export-approvals", "/api/certificate-materials/export-approvals/", "/api/certificates/acme/issue", "/api/certificates/acme/renew/", "/api/certificates/self-signed/issue",
	"/api/waf-policies", "/api/waf-policies/", "/api/access-policies", "/api/access-policies/upsert", "/api/access-policies/", "/api/rate-limit-policies", "/api/rate-limit-policies/", "/api/easy-site-profiles", "/api/easy-site-profiles/", "/api/easy-site-profiles/catalog/countries", "/api/virtual-patches/", "/api/anti-ddos/settings", "/api/anti-ddos/rule-suggestions", "/api/anti-ddos/rule-suggestions/",
	"/api/events", "/api/requests", "/api/reports/revisions", "/api/revisions", "/api/revisions/statuses", "/api/dashboard/stats", "/api/dashboard/services/", "/api/dashboard/containers/overview", "/api/dashboard/containers/logs", "/api/dashboard/containers/issues", "/api/audit",
	"/api/administration/users", "/api/administration/users/", "/api/administration/roles", "/api/administration/roles/", "/api/administration/zero-trust/health", "/api/administration/health", "/api/administration/scripts", "/api/administration/scripts/", "/api/administration/enterprise", "/api/administration/enterprise/scim-tokens", "/api/administration/enterprise/scim-tokens/", "/api/administration/support-bundle", "/api/revisions/compile", "/api/revisions/",
}
