server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location = /headers {
        add_header Content-Type text/plain;
        return 200 "host=$host\nx-forwarded-for=$http_x_forwarded_for\nx-forwarded-proto=$http_x_forwarded_proto\n";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
