apiVersion: v1
kind: Secret
metadata:
  name: tarinio-lab-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  POSTGRES_DSN: "postgres://waf:CHANGE_ME_POSTGRES_PASSWORD@postgres:5432/waf?sslmode=disable"
  CONTROL_PLANE_SECURITY_PEPPER: "CHANGE_ME_SECURITY_PEPPER"
  WAF_RUNTIME_API_TOKEN: "CHANGE_ME_RUNTIME_API_TOKEN"
  CONTROL_PLANE_BOOTSTRAP_ADMIN_PASSWORD: "CHANGE_ME_BOOTSTRAP_ADMIN_PASSWORD"
  OPENSEARCH_PASSWORD: "CHANGE_ME_OPENSEARCH_PASSWORD"
