module.exports = {
  docsSidebar: [
    'index',
    'navigator',
    {
      type: 'category',
      label: 'Core Documents',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'core-docs'}],
    },
    {
      type: 'category',
      label: 'Architecture Documents',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'architecture-docs'}],
    },
    {
      type: 'category',
      label: 'High Availability Documents',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'high-availability-docs'}],
    },
    {
      type: 'category',
      label: 'Model Documents',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'model-docs'}],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: true,
      collapsed: true,
      items: [
        'deployment-docs/index',
        'deployment-docs/docker',
        'deployment-docs/kubernetes',
        'deployment-docs/terraform',
      ],
    },
  ],
};
