module.exports = {
  docsSidebar: [
    'index',
    'navigator',
    {
      type: 'category',
      label: 'Основные документы',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'core-docs'}],
    },
    {
      type: 'category',
      label: 'Архитектурные документы',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'architecture-docs'}],
    },
    {
      type: 'category',
      label: 'Документы высокой доступности',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'high-availability-docs'}],
    },
    {
      type: 'category',
      label: 'Документы по модели',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'model-docs'}],
    },
    {
      type: 'category',
      label: 'Развертывание',
      collapsible: true,
      collapsed: true,
      items: [
        'deployment-docs/index',
        'deployment-docs/docker',
        'deployment-docs/kubernetes',
        'deployment-docs/terraform',
      ],
    },
  ],
};
