apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tarinio-lab
resources:
  - ../../manifests
  - 80-network-policies.yaml
patches:
  - path: 81-namespace-pod-security.yaml
  - path: 82-deploy-security-patch.yaml
