apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../manifests
  - 60-clickhouse.yaml
  - 61-clickhouse-security-config.yaml
patches:
  - path: 62-storage-client-security-patch.yaml
