export type WorkflowLayer = "api-runtime" | "browser-ui" | "contract";
export type Workflow = { id: string; tab: string; title: string; layer: WorkflowLayer; critical?: boolean; testTitles?: string[]; goTests?: string[] };

export const workflows: Workflow[] = [
  { id: "dashboard.stats-complete", tab: "dashboard", title: "Dashboard 24-bucket totals and top breakdowns", layer: "api-runtime", critical: true, goTests: ["TestE2EDashboardComplete/SeriesTotalsAndBreakdowns"] },
  { id: "dashboard.containers-runtime", tab: "dashboard", title: "Dashboard container overview and logs", layer: "api-runtime", critical: true, goTests: ["TestE2EDashboardComplete/ContainersOverviewAndLogs"] },
  { id: "dashboard.observation-window", tab: "dashboard", title: "Dashboard observation window consistency", layer: "api-runtime", critical: true, goTests: ["TestE2ERequestStorageParity"] },
  { id: "services.management-host-mutations", tab: "services", title: "Management host site/upstream/user/policy mutations with compile/apply cleanup", layer: "api-runtime", critical: true, goTests: ["TestE2EManagementHostMutationWorkflow"] },
  { id: "services.editor-parity", tab: "services", title: "Services editor/raw/compiler/runtime parity", layer: "api-runtime", critical: true, goTests: ["TestE2EServiceEditorParity"] },
  { id: "services.settings-roundtrip", tab: "services", title: "Services settings roundtrip and security modes", layer: "api-runtime", critical: true, goTests: ["TestE2ESiteSettingsRoundtrip"] },
  { id: "auth.login-ui-real-submit", tab: "auth", title: "Login form real submit", layer: "browser-ui", critical: true, testTitles: ["auth.login-ui-real-submit"] },
  { id: "dashboard.load", tab: "dashboard", title: "Dashboard loads", layer: "browser-ui", critical: true, testTitles: ["smoke.dashboard"] },
  { id: "dashboard.widgets", tab: "dashboard", title: "Dashboard widgets", layer: "browser-ui", critical: true },
  { id: "dashboard.series-consistency", tab: "dashboard", title: "Dashboard series labels, tooltips and totals", layer: "browser-ui", critical: true },
  { id: "dashboard.top-data", tab: "dashboard", title: "Dashboard top lists and popular errors", layer: "browser-ui", critical: true },
  { id: "dashboard.details", tab: "dashboard", title: "Dashboard widget details", layer: "browser-ui", critical: true },
  { id: "dashboard.picker-persistence", tab: "dashboard", title: "Dashboard widget picker persistence", layer: "browser-ui", critical: true },
  { id: "dashboard.layout-reset-resize", tab: "dashboard", title: "Dashboard layout reset and resize", layer: "browser-ui", critical: true },
  { id: "dashboard.resilience-states", tab: "dashboard", title: "Dashboard loading and error states", layer: "browser-ui" },
  { id: "services.list-load", tab: "services", title: "Services list", layer: "browser-ui", critical: true, testTitles: ["services.list-load services.search services.sort services.select-all"] },
  { id: "services.search", tab: "services", title: "Services search", layer: "browser-ui", testTitles: ["services.list-load services.search services.sort services.select-all"] },
  { id: "services.sort", tab: "services", title: "Services sort", layer: "browser-ui", testTitles: ["services.list-load services.search services.sort services.select-all"] },
  { id: "services.create-route", tab: "services", title: "Create editor route", layer: "browser-ui", critical: true, testTitles: ["services.create-route"] },
  { id: "services.editor-modes-search-validation-back", tab: "services", title: "Editor modes, search, validation and back", layer: "browser-ui", critical: true, testTitles: ["services.editor-modes-search-validation-back"] },
  { id: "services.export-invalid-import", tab: "services", title: "Services export and invalid import", layer: "browser-ui", critical: true, testTitles: ["services.export-invalid-import"] },
  { id: "services.save-delete-mutation", tab: "services", title: "Services save and delete mutation", layer: "browser-ui", critical: true, testTitles: ["services.save-delete-mutation"] },
  { id: "services.bulk-delete-confirm-cancel", tab: "services", title: "Services bulk delete confirm and cancel", layer: "browser-ui", critical: true, testTitles: ["services.bulk-delete-confirm-cancel"] },
  { id: "services.select-all", tab: "services", title: "Select all", layer: "browser-ui", testTitles: ["services.list-load services.search services.sort services.select-all"] },
  { id: "services.selection-navigation", tab: "services", title: "Select one/unselect all and row/edit/external navigation", layer: "browser-ui", critical: true, testTitles: ["services.selection-navigation"] },
  { id: "services.valid-import-cleanup", tab: "services", title: "Valid ENV import with API readback and cleanup", layer: "browser-ui", critical: true, testTitles: ["services.valid-import-cleanup"] },
  { id: "services.enable-disable-runtime", tab: "services", title: "Enable/disable service with API and active runtime readback", layer: "browser-ui", critical: true, testTitles: ["services.enable-disable-runtime"] },
  { id: "services.list-resilience", tab: "services", title: "Services list loading, empty and error states", layer: "browser-ui", testTitles: ["services.list-resilience"] },
  { id: "services.readonly-rbac", tab: "services", title: "Read-only Services UI and server-side write denial", layer: "browser-ui", critical: true, testTitles: ["services.readonly-rbac"] },
  { id: "services.validation-reference-matrix", tab: "services", title: "Services UI validation and API reference integrity matrix", layer: "browser-ui", critical: true, testTitles: ["services.validation-reference-matrix"] },
  { id: "services.rate-limit-modsecurity-runtime", tab: "services", title: "Rate limit and ModSecurity UI save with active runtime enforcement", layer: "browser-ui", critical: true, testTitles: ["services.rate-limit-modsecurity-runtime"] },
  { id: "services.basic-auth-mask-reveal-preview", tab: "services", title: "Basic Auth user editor, mask/reveal, TTL and template preview", layer: "browser-ui", critical: true, testTitles: ["services.basic-auth-mask-reveal-preview"] },
  { id: "services.allowlist-easy-and-raw-persistence", tab: "services", title: "Allowlist persistence through Easy and Raw editors", layer: "browser-ui", critical: true, testTitles: ["services.allowlist-easy-and-raw-persistence"] },
  { id: "services.editor-help-modals-all-controls", tab: "services", title: "All Services chapter/frame help modals keyboard and close behavior", layer: "browser-ui", critical: true, testTitles: ["services.editor-help-modals-all-controls"] },
  { id: "services.editor-draft-mode-parity-and-back-cancel", tab: "services", title: "Easy/Raw draft parity and both Back cancel paths", layer: "browser-ui", critical: true, testTitles: ["services.editor-draft-mode-parity-and-back-cancel"] },
  { id: "services.custom-error-pages-controls-preview-runtime", tab: "services", title: "Custom error page bulk controls, preview, readback and active runtime", layer: "browser-ui", critical: true, testTitles: ["services.custom-error-pages-controls-preview-runtime"] },
  { id: "services.editor-all-tabs-responsive-layout", tab: "services", title: "All editor tabs without viewport overflow or clipped controls", layer: "browser-ui", critical: true, testTitles: ["services.editor-all-tabs-responsive-layout"] },
  { id: "services.editor-keyboard-labels-and-beforeunload", tab: "services", title: "Editor labels, keyboard focus and unsaved-change guards", layer: "browser-ui", critical: true, testTitles: ["services.editor-keyboard-labels-and-beforeunload"] },
  { id: "services.antibot-template-preview-and-readback", tab: "services", title: "Anti-Bot cookie, JavaScript and captcha template previews with readback", layer: "browser-ui", critical: true, testTitles: ["services.antibot-template-preview-and-readback"] },
  { id: "services.certificate-picker-errors-export-binding", tab: "services", title: "Service certificate picker, archive error, export and TLS binding", layer: "browser-ui", critical: true, testTitles: ["services.certificate-picker-errors-export-binding"] },
  { id: "services.toggles-conditional-fields-dynamic-lists-readback", tab: "services", title: "Cross-editor toggles, conditional fields, dynamic lists and readback", layer: "browser-ui", critical: true, testTitles: ["services.toggles-conditional-fields-dynamic-lists-readback"] },
  { id: "services.virtual-patches-api-readback", tab: "services", title: "Virtual patch create, delete and API readback", layer: "browser-ui", critical: true, testTitles: ["services.virtual-patches-api-readback"] },
  { id: "services.api-resources", tab: "services", title: "Service resources", layer: "api-runtime", critical: true, testTitles: ["api.services.read-contract"], goTests: ["TestE2EServiceEditorParity"] },
  { id: "requests.read-contract", tab: "requests", title: "Requests API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2ERequestStorageParity"] },
  { id: "requests.backend-failure-visible", tab: "requests", title: "Requests backend outage returns a visible error and recovers", layer: "api-runtime", critical: true, goTests: ["TestE2ERequestsBackendFailureIsVisible"] },
  { id: "requests.read-controls", tab: "requests", title: "Requests controls", layer: "browser-ui" },
  { id: "requests.pagination-sort-detail", tab: "requests", title: "Requests pagination, sort and detail", layer: "browser-ui", testTitles: ["requests.pagination-sort-detail"] },
  { id: "requests.real-runtime-filter-pagination-detail", tab: "requests", title: "Requests real runtime security filter, pagination and detail", layer: "browser-ui", critical: true, testTitles: ["requests.real-runtime-filter-pagination-detail"] },
  { id: "requests.real-backend-failure-keeps-shell", tab: "requests", title: "Requests real backend outage keeps the application shell", layer: "browser-ui", critical: true, testTitles: ["requests.real-backend-failure-keeps-shell"] },
  { id: "bans.read-contract", tab: "bans", title: "Bans API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EBansReadContract"] },
  { id: "bans.read-controls", tab: "bans", title: "Bans controls", layer: "browser-ui" },
  { id: "bans.create-validation", tab: "bans", title: "Ban create validation", layer: "browser-ui", critical: true },
  { id: "bans.create-cancel", tab: "bans", title: "Ban create cancel", layer: "browser-ui", testTitles: ["bans.create-cancel"] },
  { id: "bans.create-extend-unban-mutation", tab: "bans", title: "Ban create, extend and unban mutation", layer: "browser-ui", critical: true, testTitles: ["bans.create-extend-unban-mutation"] },
  { id: "bans.detail-country-keyboard-pagination-cancel", tab: "bans", title: "Ban detail, country, keyboard, pagination and cancel", layer: "browser-ui", testTitles: ["bans.detail-country-keyboard-pagination-cancel"] },
  { id: "bans.duration-and-unauthorized-site-errors", tab: "bans", title: "Ban duration and missing site errors", layer: "api-runtime", critical: true, testTitles: ["bans.duration-and-unauthorized-site-errors"], goTests: ["TestE2EBansDurationAndUnauthorizedSiteErrors"] },
  { id: "bans.readonly-rbac-and-server-errors", tab: "bans", title: "Bans read-only RBAC and forbidden mutation", layer: "browser-ui", critical: true, testTitles: ["bans.readonly-rbac-and-server-errors"] },
  { id: "revisions.read-contract", tab: "revisions", title: "Revisions API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EQualityMatrix_MainPagesAndAPIs/api_revisions"] },
  { id: "revisions.read-controls", tab: "revisions", title: "Revisions controls", layer: "browser-ui" },
  { id: "revisions.compile-apply-rollback-artifact", tab: "revisions", title: "Revision compile, apply, rollback and artifact identity", layer: "api-runtime", critical: true, testTitles: ["revisions.compile-apply-rollback-artifact"], goTests: ["TestE2EServiceEditorParity"] },
  { id: "revisions.validation-delete-active-and-missing-errors", tab: "revisions", title: "Revision active delete and missing apply errors", layer: "api-runtime", critical: true, testTitles: ["revisions.validation-delete-active-and-missing-errors"], goTests: ["TestE2ERevisionsValidationDeleteActiveAndMissingErrors"] },
  { id: "revisions.status-and-delete-confirm-cancel-ui", tab: "revisions", title: "Revision status modal and delete cancel", layer: "browser-ui", testTitles: ["revisions.status-and-delete-confirm-cancel-ui"] },
  { id: "revisions.apply-and-delete-success-ui", tab: "revisions", title: "Revision apply, rollback and delete success through UI", layer: "browser-ui", critical: true, testTitles: ["revisions.apply-and-delete-success-ui"] },
  { id: "anti-ddos.read-contract", tab: "anti-ddos", title: "Anti-DDoS API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EManagementHostIsExcludedFromGlobalL7RateLimit"] },
  { id: "anti-ddos.help-modal", tab: "anti-ddos", title: "Anti-DDoS help modal", layer: "browser-ui" },
  { id: "anti-ddos.save-validation-restore", tab: "anti-ddos", title: "Anti-DDoS save, validation and restore", layer: "browser-ui", critical: true, testTitles: ["anti-ddos.save-validation-restore"] },
  { id: "anti-ddos.management-rate-limit-exclusion", tab: "anti-ddos", title: "Management host rate-limit exclusion", layer: "api-runtime", critical: true, goTests: ["TestE2EManagementHostIsExcludedFromGlobalL7RateLimit"] },
  { id: "anti-ddos.all-groups-roundtrip-restore", tab: "anti-ddos", title: "All L4, L7 and adaptive model settings roundtrip", layer: "browser-ui", critical: true, testTitles: ["anti-ddos.all-groups-roundtrip-restore"] },
  { id: "anti-ddos.server-validation-no-partial-save", tab: "anti-ddos", title: "Server validation and normalization without partial save", layer: "api-runtime", critical: true, testTitles: ["anti-ddos.server-validation-no-partial-save"], goTests: ["TestE2ERecoveryFlow_BadConfigThenRepair/RejectInvalidAntiDDoSConfig"] },
  { id: "anti-ddos.rule-suggestions-create-list-detail-status", tab: "anti-ddos", title: "Rule suggestion create, list, detail and status", layer: "api-runtime", testTitles: ["anti-ddos.rule-suggestions-create-list-detail-status"], goTests: ["TestE2EAPIExtendedMatrix/CertIssueAndSuggestions"] },
  { id: "anti-ddos.logs-refresh-detail-or-empty", tab: "anti-ddos", title: "Model logs refresh, detail and empty state", layer: "browser-ui", testTitles: ["anti-ddos.logs-refresh-detail-or-empty"] },
  { id: "owasp-crs.read-contract", tab: "owasp-crs", title: "OWASP CRS API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EOWASPCRSCheckUsesOfficialReleaseDigest"] },
  { id: "owasp-crs.read-controls", tab: "owasp-crs", title: "OWASP CRS controls", layer: "browser-ui" },
  { id: "owasp-crs.official-digest", tab: "owasp-crs", title: "Official release digest verification", layer: "api-runtime", critical: true, goTests: ["TestE2EOWASPCRSCheckUsesOfficialReleaseDigest"] },
  { id: "owasp-crs.check-update-hourly-persistence-restore", tab: "owasp-crs", title: "CRS check, update and hourly persistence with restore", layer: "browser-ui", critical: true, testTitles: ["owasp-crs.check-update-hourly-persistence-restore"] },
  { id: "owasp-crs.api-validation-and-disabled-busy-state", tab: "owasp-crs", title: "CRS validation and busy disabled controls", layer: "browser-ui", testTitles: ["owasp-crs.api-validation-and-disabled-busy-state"] },
  { id: "tls.read-contract", tab: "tls", title: "TLS API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2ESecurityAndTLSMatrix/TLSLifecycle"] },
  { id: "tls.read-controls", tab: "tls", title: "TLS controls", layer: "browser-ui" },
  { id: "tls.certificate-binding-create-delete", tab: "tls", title: "TLS certificate and binding create/delete", layer: "browser-ui", critical: true, testTitles: ["tls.certificate-binding-create-delete"] },
  { id: "tls.self-signed-selection-detail-validation", tab: "tls", title: "Self-signed issuance, selection and validation", layer: "browser-ui", critical: true, testTitles: ["tls.self-signed-selection-detail-validation"] },
  { id: "tls.auto-renew-persistence-and-validation", tab: "tls", title: "TLS auto-renew persistence and validation", layer: "browser-ui", testTitles: ["tls.auto-renew-persistence-and-validation"] },
  { id: "tls.acme-conditional-fields-and-disabled-errors", tab: "tls", title: "ACME conditional fields and disabled errors", layer: "browser-ui", testTitles: ["tls.acme-conditional-fields-and-disabled-errors"] },
  { id: "tls.import-export-step-up-errors-and-mobile-layout", tab: "tls", title: "TLS import error, export step-up modal and mobile forms", layer: "browser-ui", critical: true, testTitles: ["tls.import-export-step-up-errors-and-mobile-layout"] },
  { id: "tls.upload-and-valid-archive-import", tab: "tls", title: "TLS material upload and valid archive import", layer: "browser-ui", critical: true, testTitles: ["tls.upload-and-valid-archive-import"] },
  { id: "administration.read-contract", tab: "administration", title: "Administration API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EQualityMatrix_MainPagesAndAPIs/api_administration_roles", "TestE2EQualityMatrix_MainPagesAndAPIs/api_administration_scripts", "TestE2EQualityMatrix_MainPagesAndAPIs/api_administration_users"] },
  { id: "administration.read-controls", tab: "administration", title: "Administration controls", layer: "browser-ui" },
  { id: "administration.user-create-edit-readback", tab: "administration", title: "Administration user create/edit/readback", layer: "browser-ui", critical: true, testTitles: ["administration.user-create-edit-readback"] },
  { id: "administration.role-create-edit-readback", tab: "administration", title: "Administration role create/edit/readback", layer: "browser-ui", critical: true, testTitles: ["administration.role-create-edit-readback"] },
  { id: "administration.enterprise-scim-scripts", tab: "administration", title: "Enterprise SCIM and scripts matrix", layer: "api-runtime", critical: true, goTests: ["TestE2EAPIEnterpriseMatrix/EnterpriseAdminEndpoints", "TestE2EAPIEnterpriseMatrix/SCIMSurface", "TestE2EAPIEnterpriseMatrix/AdministrationScriptsRunDownload"] },
  { id: "events.read-contract", tab: "events", title: "Events API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EAPISchemaContracts/EventsContract"] },
  { id: "events.read-controls", tab: "events", title: "Events controls", layer: "browser-ui" },
  { id: "events.api-filter-pagination-detail-contract", tab: "events", title: "Events filter, pagination and detail API contract", layer: "api-runtime", critical: true, goTests: ["TestE2EEventsAPIFilterPaginationDetailContract"] },
  { id: "events.browser-pagination-detail-keyboard", tab: "events", title: "Events pagination, detail and keyboard", layer: "browser-ui", testTitles: ["events.browser-pagination-detail-keyboard"] },
  { id: "events.loading-empty-error-malformed", tab: "events", title: "Events resilience states", layer: "browser-ui", testTitles: ["events.loading-empty-error-malformed"] },
  { id: "activity.read-contract", tab: "activity", title: "Activity API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EAPISchemaContracts/AuditContract"] },
  { id: "activity.read-controls", tab: "activity", title: "Activity controls", layer: "browser-ui" },
  { id: "activity.api-filter-pagination-and-critical-mutations", tab: "activity", title: "Audit filters, pagination and critical actions", layer: "api-runtime", critical: true, goTests: ["TestE2EActivityAPIFilterPaginationAndCriticalMutations"] },
  { id: "activity.presets-submit-pagination-keyboard", tab: "activity", title: "Activity presets, pager and keyboard", layer: "browser-ui", testTitles: ["activity.presets-submit-pagination-keyboard"] },
  { id: "activity.loading-empty-error-malformed", tab: "activity", title: "Activity resilience states", layer: "browser-ui", testTitles: ["activity.loading-empty-error-malformed"] },
  { id: "settings.read-contract", tab: "settings", title: "Settings API read contract", layer: "api-runtime", critical: true, goTests: ["TestE2EQualityMatrix_MainPagesAndAPIs/api_settings_runtime"] },
  { id: "settings.read-controls", tab: "settings", title: "Settings controls", layer: "browser-ui" },
  { id: "settings.validation-no-partial-save", tab: "settings", title: "Settings validation without partial save", layer: "browser-ui" },
  { id: "settings.runtime-toggle-persistence-restore", tab: "settings", title: "Runtime toggle persistence and restore", layer: "browser-ui", critical: true, testTitles: ["settings.runtime-toggle-persistence-restore"] },
  { id: "settings.language-all-locales-persistence-restore", tab: "settings", title: "All language locales persistence and restore", layer: "browser-ui", critical: true, testTitles: ["settings.language-all-locales-persistence-restore"] },
  { id: "settings.storage-roundtrip-indexes-and-no-partial-save", tab: "settings", title: "Storage retention, indexes and transactional validation", layer: "browser-ui", critical: true, testTitles: ["settings.storage-roundtrip-indexes-and-no-partial-save"] },
  { id: "settings.security-roundtrip-direct-ip-and-validation", tab: "settings", title: "Security and direct-IP settings", layer: "browser-ui", critical: true, testTitles: ["settings.security-roundtrip-direct-ip-and-validation"] },
  { id: "settings.logging-backends-routing-migration-roundtrip", tab: "settings", title: "Logging backends, routing and migration", layer: "browser-ui", testTitles: ["settings.logging-backends-routing-migration-roundtrip"] },
  { id: "settings.secrets-masked-save-and-toggle", tab: "settings", title: "Masked secrets save and visibility", layer: "browser-ui", critical: true, testTitles: ["settings.secrets-masked-save-and-toggle"] },
  { id: "settings.management-hosts-validation-status-restore", tab: "settings", title: "Management hosts ownership, version and status", layer: "browser-ui", critical: true, testTitles: ["settings.management-hosts-validation-status-restore"] },
  { id: "settings.appearance-preview-save-reload-restore", tab: "settings", title: "Login, 2FA and healthcheck appearance", layer: "browser-ui", testTitles: ["settings.appearance-preview-save-reload-restore"] },
  { id: "settings.update-check-success-disabled-offline", tab: "settings", title: "Update check success, disabled and offline", layer: "browser-ui", testTitles: ["settings.update-check-success-disabled-offline"] },
  { id: "cross-module.settings-services-tls-antiddos-compile-apply-audit", tab: "cross-module", title: "Cross-module compile, apply, rollback and audit", layer: "browser-ui", critical: true, testTitles: ["cross-module.settings-services-tls-antiddos-compile-apply-audit"] },
  { id: "cross-resilience-429-403-5xx-malformed-and-slow-api", tab: "cross-module", title: "Cross-module API resilience and slow responses", layer: "browser-ui", critical: true, testTitles: ["cross-resilience-429-403-5xx-malformed-and-slow-api"] },
  { id: "cross-i18n-all-locales-core-labels-errors-and-modals", tab: "cross-module", title: "Cross-module localization", layer: "browser-ui", testTitles: ["cross-i18n-all-locales-core-labels-errors-and-modals"] },
  { id: "cross-security-headers-cookies-and-no-secret-leak", tab: "cross-module", title: "Security headers, cookies and secret leakage", layer: "browser-ui", critical: true, testTitles: ["cross-security-headers-cookies-and-no-secret-leak"] },
  { id: "cross-security.readonly-rbac-and-session-expiry-return-login", tab: "cross-module", title: "Cross-module RBAC and session expiry", layer: "browser-ui", critical: true, testTitles: ["cross-security.readonly-rbac-and-session-expiry-return-login"] },
  { id: "revisions.detail-modal-close", tab: "revisions", title: "Revision detail modal close", layer: "browser-ui" },
  { id: "revisions.clear-statuses-control", tab: "revisions", title: "Revision clear statuses control", layer: "browser-ui", testTitles: ["revisions.clear-statuses-control"] },
];
